# Generated by Django 6.1.1 on 2026-09-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'магазин', 'verbose_name_plural': 'магазини'},
        ),
    ]
