# Generated by Django 6.1.1 on 2026-09-17 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='име')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='име')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='забележка')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=7, verbose_name='количество')),
                ('unit', models.CharField(choices=[('pcs', 'бр.'), ('lt', 'л'), ('ml', 'мл'), ('kg', 'кг'), ('gr', 'гр'), ('m', 'м'), ('oz', 'ун')], default='pcs', max_length=5, verbose_name='мерни единици')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='спешно')),
                ('category', models.ManyToManyField(related_name='items', to='items.category', verbose_name='категория')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.store', verbose_name='магазин')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.shoppinglist')),
            ],
        ),
    ]
