# Generated by Django 6.1.1 on 2026-09-19 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_shoppinglist_user'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукти'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'списък', 'verbose_name_plural': 'списъци'},
        ),
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.store', verbose_name='магазин'),
        ),
    ]
