# Generated by Django 6.1.1 on 2026-09-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_options_alter_shoppinglist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='items.category', verbose_name='категория'),
        ),
    ]
