# Generated by Django 6.1.1 on 2026-09-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_bought',
            field=models.BooleanField(default=False, verbose_name='закупен'),
        ),
    ]
