# Generated by Django 6.1.1 on 2026-09-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_created_at_item_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bought_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
